package main;

public enum Contexte {
	
	ATTAQUER,
	VOLER_EQUIP,
	EFFET_NEGATIF_SUR_AUTRES,
	EFFET_POSITIF_SUR_AUTRES,
	ACTIVER_EFFET_LIEU,
	EFFET_BOB,
	LANCER_DES_4,
	LANCER_DES_6, CHOISIR_VISION, CHOISIR_ACTION
	
}
